#!/usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)
underscore=$(tput smul)

cat <<EOF
Prepare and run multiple Last Oasis dedicated servers with docker-compose

${bold}USAGE
  ${normal}last-oasis-compose <options> [command]

${bold}OPTIONS
  ${normal}The following options are available:

  -v          Docker volume name
  -i <image>  Docker image name

${bold}COMMANDS
  ${normal}The following commands are available:

  help        Show this help screen
  build       Build the docker image used by compose
  login       Login to steam. Requires PW and 2FA-Code when when runnig first time
  install     Create docker volme, build docker image, download and install last oasis to volume.
  update      Update Last Oasis
  up          Start all the servers
  down        Stop all the servers
  logs        Tail combined logs from all compose services
  backup      Create a tarball of save data via the maintenance service

${bold}ENVIRONMENT VARIABLES:
  ${normal}The following environment variables are available:

    ${underscore}DOCKER_IMAGE${normal}            (overwritten by '-i' option) [optional]
      Docker image name to use. (Default: "last-oasis")

    ${underscore}DOCKER_VOLUME${normal}           (overwritten by '-v' option) [optional]
      Docker volume name to use. (Default: "last-oasis-volume")

${bold}EXAMPLES
  ${normal}# Create docker volme, build docker image, download and install last oasis to volume.
  last-oasis-compose install

  # Update Last Oasis server
  last-oasis-compose update

  # Run multiple Last Oasis Servers in background
  last-oasis-compose up

  # Stop all running Last Oasis servers
  last-oasis-compose down

${bold}NOTE
  ${normal}Configuration of your realm and oasis must be done at: https://myrealm.lastoasis.gg/.

${bold}AUTHORS
  ${normal}Patrick Helm is the main author.
  The whole list of contributors can be found at: https://github.com/deradon/last-oasis-docker-dedicated-server.

${bold}HELP
  ${normal}For additional help please see: https://github.com/deradon/last-oasis-docker-dedicated-server
EOF
