#!/usr/bin/env bash

docker_create_volume(){
  run "docker volume create --name $DOCKER_VOLUME"
}

docker_build_image(){
  run "docker build . -t $DOCKER_IMAGE -f Dockerfile"
}

docker_debug(){
  run "docker run \
    --publish $SERVER_PORT:$SERVER_PORT/tcp \
    --publish $SERVER_QUERY_PORT:$SERVER_QUERY_PORT/tcp \
    --publish $SERVER_PORT:$SERVER_PORT/udp \
    --publish $SERVER_QUERY_PORT:$SERVER_QUERY_PORT/udp \
    --interactive \
    --tty \
    --rm \
    -e 'TERM=xterm-256color' \
    -v $DOCKER_VOLUME:/mnt/steam/ \
    --entrypoint /bin/bash
    $DOCKER_IMAGE \
    $1"
}

docker_run(){
  run "docker run \
    --interactive \
    --tty \
    --rm \
    -e 'TERM=xterm-256color' \
    -v $DOCKER_VOLUME:/mnt/steam/ \
    $DOCKER_IMAGE \
    $1"
}

docker_compose_maintenance(){
  run "docker-compose run maintenance $1"
}

docker_compose(){
  run "docker-compose $1"
}

docker_backup(){
  HOST_BACKUP_DIR="${HOST_BACKUP_DIR:-$(pwd)/backups}"
  run "mkdir -p '$HOST_BACKUP_DIR'"
  run "docker run \
    --rm \
    -v $DOCKER_VOLUME:/mnt/steam/ \
    -v '$HOST_BACKUP_DIR':/backups \
    -e BACKUP_DIR=/backups \
    $DOCKER_IMAGE \
    backup"
}

docker_logs(){
  LOG_PATH="/mnt/steam/last-oasis/Mist/Saved/Logs/Mist.log"
  run "docker run \
    --rm \
    -v $DOCKER_VOLUME:/mnt/steam/ \
    --entrypoint /bin/sh \
    $DOCKER_IMAGE \
    -c 'test -f $LOG_PATH && tail -n 200 $LOG_PATH || echo \"[ERROR] Log file not found at $LOG_PATH\"'"
}
